config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  # Routes for users to register and edit their logins & profiles
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Routes for users to CRUD their own timecards:
  resources :timecards

  # Routes for the document library
  resources :documents, except: %i[new edit]

  # Routes for lessons
  resources :completions, only: :destroy
  resources :lessons do
    member do
      post 'completions', to: 'completions#create'
      get 'users'
    end
  end

  # Administration related routes:
  scope '/admin' do
    resources :users, except: %i[new create] do
      member do
        get 'lessons'
        patch 'deactivate'
        patch 'reactivate'
        patch 'approve'
        delete 'reject'
      end
    end

    # Training completions index
    resources :completions, only: :index

    # Admin timecard index and filters
    get 'timecards/(:user_id)', to: 'timecards#admindex', as: 'admin_timecards'

    # Bulletin management
    resources :bulletins, except: %i[show index]

    # Document library
    resources :documents, only: %i[new edit]
  end
end

app/views/pages/home/_create_bulletin.html.erb
<%= button_to "Post new bulletin", new_bulletin_path, method: :get, class: "btn btn-block btn-outline-primary my-2" %>
<p class="text-muted text-center"><small>Bulletins are sorted by date created/modified, newest to oldest.</small></p>

app/views/pages/home/_last_workday.html.erb
<div class="m-1">
  <p>
    <%= message %>
  </p>
  <%= button_to "Log a workday", new_timecard_path, class: "btn btn-block btn-dark", method: :get %>
  <hr>
</div>

app/views/pages/home/_logged_in.html.erb
<!-- All of these methods are defined in pages_helper.rb -->
<div class="col-md-3">
  <%= pending_users %>
  <%= weekly_timecard_stats %>
  <%= last_workday %>
</div>

<div class="col-md-9">
  <%= bulletins %>
  <%= create_bulletin %>
</div>

app/views/pages/home/_logged_out.html.erb
<div class="col-xl-8 offset-xl-2">
  <div class="card">
    <h5 class="card-header">You are not currently signed in.</h5>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary px-2 btn-block" %>
        </div>
        <div class="col">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-success px-2 btn-block" %>
        </div>
      </div>
      <p class="mt-3 card-text">If you are looking for the Monroe County Sheriff's public website, it can be found <a href= "http://monroetnsheriff.com/">here.</a></p>
    </div>
  </div>
</div>

app/views/pages/home/_pending_users.html.erb
<div class="m-1">
  <h6><%= pluralize(@pending_count, "user") %> awaiting approval.</h6>
  <p>These users will not be able to sign in until they are approved by either a trainer or an administrator.</p>
  <%= button_to "Manage Users", users_path(anchor: 'Pending'), class: "btn btn-block btn-primary my-2", method: :get %>
  <hr>
</div>

app/views/pages/home/_timecard_stats.html.erb
<div class="m-1">
  <p>
    <%= pluralize(user_count, 'person has', 'people have')%> logged a combined total
    of <%= pluralize(total_time, 'hour') %> in the past 7 days.
  </p>
</div>