config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  # Routes for users to register and edit their logins & profiles
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Routes for users to CRUD their own timecards:
  resources :timecards

  # Routes for the document library
  resources :documents, except: %i[new edit]

  # Routes for lessons
  resources :completions, only: :destroy
  resources :lessons do
    member do
      post 'completions', to: 'completions#create'
      get 'users'
    end
  end

  # Administration related routes:
  scope '/admin' do
    resources :users, except: %i[new create] do
      member do
        get 'lessons'
        patch 'deactivate'
        patch 'reactivate'
        patch 'approve'
        delete 'reject'
      end
    end

    # Training completions index
    resources :completions, only: :index

    # Admin timecard index and filters
    get 'timecards/(:user_id)', to: 'timecards#admindex', as: 'admin_timecards'

    # Bulletin management
    resources :bulletins, except: %i[show index]

    # Document library
    resources :documents, only: %i[new edit]
  end
end

app/models/user.rb
# frozen_string_literal: true

# Are you happy, rubocop?
class User < ApplicationRecord
  # Associations:
  has_many :timecards, dependent: :destroy
  has_many :completions, dependent: :destroy
  has_many :lessons, through: :completions
  has_many :bulletins

  # Validations:
  # (Devise handles most of them. I only need to validate my custom fields)
  # Validates first and last names, 30 characters, a-z/A-Z, hyphens, and spaces.
  NAME_REGEX = /\A[a-z,\-, ]{1,30}\z/i.freeze
  validates_format_of :first_name, with: NAME_REGEX
  validates_format_of :last_name,  with: NAME_REGEX
  # Validates badge number, Either X-(2 digits) with or without dash. If no
  # dash, add it later.
  validates_format_of :badge_number, with: %r{\A(x\-?\d{1,2}|7\d{2}|N/?A)\z}i

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Callbacks:
  before_save :format_string_fields
  after_create :set_default_role

  # Enumerate roles for convenience. They're stored in the database as
  # integers.
  enum role: %i[pending deputy trainer admin]

  # Custom methods:

  # Returns full name in a view-friendly format.
  def first_last(length = 25)
    "#{first_name} #{last_name}".truncate(length, omission: '...')
  end

  # Returns full name in a different view friendly format.
  def last_first(length = 25)
    "#{last_name}, #{first_name}".truncate(length, omission: '...')
  end

  # Admins are trainers too.
  def trainer?
    super || admin?
  end

  # Devise method overwrite - Makes sure user is approved and not deactivated.
  def active_for_authentication?
    super && !pending? && !deleted_at
  end

  # Modify the devise flash message for unapproved users.
  def inactive_message
    if pending?
      :not_approved
    elsif deleted_at
      :deleted_account
    else
      super
    end
  end

  # Soft delete method, used to overwrite the default destroy method and stop
  # users from deleting their accounts. Ensures the last admin can't deactivate
  # themselves.
  def deactivate
    if admin? && User.where(role: :admin).count <= 1
      false
    else
      update(deleted_at: Time.zone.now, role: :deputy)
    end
  end

  def reactivate
    update_attribute(:deleted_at, nil)
  end

  # Override the default destroy method to ensure the last admin doesn't delete
  # their account:
  def destroy
    if admin? && User.where(role: :admin).count <= 1
      false
    else
      super
    end
  end

  def approve
    if pending?
      update(role: :deputy)
    else
      false
    end
  end

  def reject
    if pending?
      destroy
    else
      false
    end
  end

  private

  # Callback: New users are set to pending.
  def set_default_role
    self.role = :pending
  end

  # Callback: Fixes capitalization and formatting.
  def format_string_fields
    self.first_name   = format_name(first_name, false)
    self.last_name    = format_name(last_name, true)
    self.badge_number = format_badge(badge_number)
  end

  def format_name(name, is_last = false)
    # Capitalization:
    name = name.downcase.split.map(&:capitalize).join(' ')
    # replace multiple spaces with a single one:
    name = name.gsub(/ {2,}/, ' ')
    # remove spaces from the end:
    name = name.gsub(/ \z/, '')
    if is_last
      # Uppercase for I, II, IV, etc:
      name = name.gsub(/[i,v,x]{1,3}\z/i, &:upcase)
    end
    name
  end

  def format_badge(badge)
    # Uppercase badge number:
    badge = badge.upcase
    # Add a dash to the badge number (X01 -> X-01):
    badge = badge.gsub(/X(?<num>\d{1,2})/, 'X-\k<num>')
    # Strip leading 0s from X-Badges (i.e. X-01 -> X-1):
    badge = badge.gsub(/X-0(?<num>\d)/, 'X-\k<num>')
    # Change NA to N/A for consistency:
    badge.gsub(/NA/, 'N/A')
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    if resource.deactivate
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      set_flash_message :notice, :destroyed if is_flashing_format?
      yield resource if block_given?
      respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
    else
      flash[:alert] =
        'Please create another administrator before deactivating your account.'
      redirect_to edit_user_registration_path
    end
  end
end

app/controllers/users_controller.rb
# Handles user management for admins
class UsersController < ApplicationController
  # All of these actions are part of the admin menu. Normal account management
  # is handled by Devise.

  def index
    authorize User

    @users_active =
      User.where(role: %i[deputy trainer admin], deleted_at: nil)
          .order(role: :desc, last_name: :asc)
    @users_pending =
      User.where(role: :pending, deleted_at: nil)
          .order(:last_name)
    @users_deactivated =
      User.where.not(deleted_at: nil)
          .order(:last_name)
  end

  def show
    @user = user
  end

  def edit
    @user = user
  end

  def update
    @user = user
    if @user.update(user_params)
      flash[:success] = 'User updated!'
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'Could not update user!'
      render :edit
    end
  end

  def destroy
    @user = user
    if @user.destroy
      flash[:success] = 'User deleted!'
      redirect_to users_path
    else
      flash[:danger] =
        'Cannot delete the last administrator. Please create another first!'
      redirect_to user_path(@user)
    end
  end

  # Custom action allowing trainers to approve pending users
  def approve
    @user = user
    if @user.approve
      flash[:success] =
        "User approved! Their role has been set to deputy, and they can now
        log in."
    else
      flash[:danger] = 'Could not approve user.'
    end

    redirect_to user_path(@user)
  end

  # Custom action allowing trainers to reject pending users.
  def reject
    @user = user
    if @user.reject
      flash[:success] =
        "User rejected! Their account has been deleted, and they will not be
        able to log in."
      redirect_to users_path
    else
      flash[:danger] = 'Could not reject user.'
      redirect_to user_path(@user)
    end
  end

  # Preferred method for turning people off:
  def deactivate
    @user = user
    if @user.deactivate
      flash[:success] = 'User deactivated.'
      redirect_to user_path(@user)
    else
      flash[:danger] =
        'Please create another administrator before deactivating this account.'
      redirect_to edit_user_path(@user)
    end
  end

  # because it lets you turn them back on again.
  def reactivate
    @user = user
    if @user.reactivate
      flash[:success] = 'User reactivated! Their role has been set to deputy.'
      redirect_to user_path(@user)
    else
      flash[:alert] = 'Could not reactivate user.'
      redirect_to edit_user_path(@user)
    end
  end

  # Index training requirements by completion status, based on a particular user
  def lessons
    @user = user
    authorize @user
    @lessons_complete = @user.lessons.all.order(:title)
    @lessons_incomplete = Lesson.all.order(:title).to_a - @lessons_complete.to_a
  end

  private

  def user
    user = User.unscoped.find(params[:id])
    authorize user
    user
  end

  def user_params
    params.require(:user)
          .permit(:first_name, :last_name, :badge_number, :role, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_approve_buttons.html.erb
<p class="card-text">This person has signed up, but they must be approved by a trainer or an administrator before they will be able to log in. If you reject them, their account will be deleted irreversibly.</p>
<div class="row justify-content-center my-3">
  <div class="col">
    <%= button_to("Approve", approve_user_path(@user), method: :patch, class: "btn btn-success btn-block") %>
  </div>
  <div class="col">
    <%= button_to("Reject", reject_user_path(@user), method: :delete, class: "btn btn-danger btn-block", data: { confirm: "Are you sure you want to delete this account?" } ) %>
  </div>
</div>

app/views/users/_users_table.html.erb
<% if users.any? %>
  <hr class="mt-3" />
  <h4 id="<%= which_list %>"><%= which_list %>:</h4>
  <div class="row my-2">
    <div class="col-sm-6">
      <table class="table table-hover">
        <thead>
          <tr class="row">
            <th scope="col" class="col-6">Name</th>
            <th scope="col" class="col-3"><%= 'Role' if which_list =="Active" %></th>
            <th scope="col" class="col-3">Badge</th>
          </tr>
        </thead>
        <% users.each do |u| %>
          <tr class="row" onclick="window.location='<%= user_path(u) %>'"> 
            <td class="col-6"><%= link_to u.last_first(40), user_path(u) %></td>
            <td class="col-3" ><%= u.role.capitalize if which_list == "Active" %></td>
            <td class="col-3"><%= u.badge_number %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-sm-6">
      <% if which_list == "Active" %>
        <h6>Deputies:</h6>
        <ul>
          <li>Can see all training videos and mark them as complete.</li>
          <li>Can see their own training records.</li>
          <li>Can log, review,  edit, and delete their own timecards.</li>
          <li>Cannot access anything under the "Administration" menu.</li>
          <li>Can see and download anything in the documents library, but cannot
            upload to it.</li>
        </ul>
        <h6>Trainers:</h6>
        <ul>
          <li>Can do everything a deputy can.</li>
          <li>Can create, edit, and delete training videos.</li>
          <li>Can view anyone's training records, timecards, and details.</li>
          <li>Have view access to the "Administration" menu.</li>
          <li>Cannot edit any user details, including role and activation.</li>
          <li>Can approve or reject pending signups.</li>
          <li>Can upload new files to the document library.</li>
        </ul>
        <h6>Admins:</h6>
        <p>Be careful who you give this role to. You should't need more than a couple people with these permissions. If these rules could be improved, let me know! <a href="mailto:robert@buchberger.cc">robert@buchberger.cc</a></p> 
        <ul>
          <li>Can do everything a trainer can.</li>
          <li>Can edit user information such as name, badge number, and email address.</li>
          <li>Can set any user's role to anything.</li>
          <li>Can deactivate and reactivate anybody.</li>
          <li>Can delete any user account, even though they should almost never do it.</li>
          <li>Can delete (but not create or edit!) any timecard.</li>
        </ul>
      <% elsif which_list == "Pending" %>
        <p>These people have signed up, but they need to be approved (by a trainer or an admin) before they can do anything. Click their name, look for the big buttons. If you're having a lot of spam signups, there are some things that can be done to mitigate it. Send me an email: <a href="mailto:robert@buchberger.cc">robert@buchberger.cc</a></p>
      <% elsif which_list == "Deactivated" %>
        <p>These people have been deactivated, either by themselves or an admin. They will be unable to log in, but their records will
          be saved alongside everyone else. An admin can activate them again under "edit details".</p>
        <p><strong>There's no reason to delete real accounts that were ever used by a real person.</strong> Deactivate them instead, and their records will be maintained as long as the site still functions.</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h4 class="display-4 text-center my-4">Editing <%= @user.first_name %>'s profile.</h4>
<%= validation_fails @user %>
<%= form_for @user do |f| %>
  <div class="row justify-content-center">
    <div class="col-md-4 field form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name,  class: "form-control", required: true %>
    </div>
    <div class="col-md-4 field form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name,  class: "form-control", required: true %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-4 field form-group">
      <%= f.label :badge_number %>
      <%= f.text_field :badge_number,  class: "form-control", required: true %>
    </div>
    <div class="col-md-4 field form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", required: true %>
    </div>
  </div>
  <% unless @user.deleted_at || @user.pending? %>
    <div class="row justify-content-center">  
      <div class="col-md-8 my-4 form-check form-check-inline text-center">
        <div class="card p-3 my-3">
          <h4 class="card-title text-left">Role</h4>
          <p class="card-text text-left">This is how you control which people can do which things.</p>
          <ul class="text-left card-text">
            <li><strong>Deputy:</strong> Deputies are basic users. They can see all training videos, log completed training, and log, edit, and delete their own timecards. They can't edit videos, and they can't see any other users.</li>
            <li><strong>Trainer:</strong> Trainers have full control over training videos, can see all user information, and can approve or reject pending signups, but they can't edit user details or deactivate them.</li>
            <li><strong>Administrator:</strong> These users can do nearly anything, including permanent deletion of user accounts (which you shouldn't do). Don't give someone this role unless they need it. </li>
          </ul>
          <div class="row justify-content-center my-3">
            <label class="mx-auto form-check-label">
              <%= f.radio_button :role, :deputy, class: "form-check-input" %>
              Deputy
            </label>
            <label class="form-check-label mx-auto">
              <%= f.radio_button :role, :trainer, class: "form-check-input" %>
              Trainer
            </label>
            <label class="mx-auto form-check-label">
              <%= f.radio_button :role, :admin, class: "form-check-input" %>
              Administrator
            </label>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-md-8 actions form-group">
      <%= f.submit "Update", class: "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
 
<% end %>
<div class="row justify-content-center">
  <div class="card border-primary m-3 p-3">
    <% if @user.deleted_at %>
      <h4 class="card-title">This user's account has been deactivated.</h4>
      <p class="card-text"><%= @user.first_last %> was deactivated on <%= @user.deleted_at.strftime("%B %e, %Y") %>. Deactivated users can't log in, and they won't show up in most of the site, but all their records will be kept. If you reactivate them, they will have normal access again.</p>
      <%= button_to "Reactivate User", reactivate_user_path(@user), class: "btn btn-primary btn-block", method: :patch %>
    <% elsif policy(@user).approve? %>
      <h4 class="card-title">User not approved yet.</h4>
      <%= render "approve_buttons" %>
    <% else %>
      <h4 class="card-title">Deactivate user</h4>
      <p><%= @user.first_last %> is currently active. If you deactivate a user, their records will not be deleted, but they will not be able to log in and they will not show up in most parts of the site.</p>
      <%= button_to "Deactivate User", deactivate_user_path(@user), class: "btn btn-secondary btn-block", method: :patch %>
    <% end %>
  </div>
</div>
<% unless policy(@user).approve? %>
  <div class="row justify-content-center">
    <div class="card border-danger m-3 p-3">
        <h4 class="card-title">Account Deletion</h4>
        <p class="card-text">Warning: This cannot be undone. All of this person's training records and timecards will be irreversibly deleted. If this was a real account used by a real person, you shouldn't do this; use the deactivate button above instead.</p>
        <div class="row justify-content-center">
            <%= button_to "Delete user", user_path, data: { confirm: "Are you sure you want to delete this user account?" }, method: :delete, class: "btn btn-danger btn-sm" %>
        </div>
    </div>
  </div>
<% end %>
<div class="row justify-content-center">
  <%= link_to "Back", :back, class: "m-5" %>
</div>

app/views/users/index.html.erb
<h4 class="display-4 text-center my-4">Everybody</h4>
<%= render partial: 'users_table', locals: {which_list: 'Active', users: @users_active} %>
<%= render partial: 'users_table', locals: {which_list: 'Pending', users: @users_pending} %>
<%= render partial: 'users_table', locals: {which_list: 'Deactivated', users: @users_deactivated} %>

app/views/users/lessons.html.erb
<h4 class="display-4 text-center">Training Records: <%= @user.first_last %></h4>
<h5 class="mt-4">Complete:</h5>
<% if @lessons_complete.any? %>
  <ul>
    <% @lessons_complete.each do |l| %>
      <li><%= link_to l.title, lesson_path(l) %></li>
    <% end %>
  </ul>
<% else %>
  <p>This person hasn't finished any videos yet.</p>
<% end %>
<h5 class="mt-4">Not Complete:</h5>
<% if @lessons_incomplete.any? %>
  <ul>
    <% @lessons_incomplete.each do |l| %>
      <li><%= link_to l.title, lesson_path(l) %></li>
    <% end %>
  </ul>
<% else %>
  <p>This person has completed all training videos.</p>
<% end %>
<hr>
<div class="row">
  <%= link_to "View user details", user_path(@user), class: "mx-auto" %>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center">
  <div class="col align-self-center col-md-8 card"> 
    <h4 class="display-4 card-title text-center"><%= @user.first_last %> </h1>
    <h4 class="card-subtitle text-center"><%= @user.deleted_at ? "Deactivated" : @user.role.capitalize %></h2>
    <div class="card-body">
      <p><strong>Badge number:</strong> <%= @user.badge_number %> </p>
      <p><strong>Email address:</strong> <%= @user.email %> </p>
      <p><strong>Account created:</strong> <%= @user.created_at.strftime("%b %d, %Y") %></p>
      <% unless policy(@user).approve? %>
        <p><strong>Last signed in:</strong> <%= @user.current_sign_in_at ? @user.current_sign_in_at.strftime("%b %d, %Y") : "None" %></p>
        <p><strong>Number of times signed in:</strong> <%= @user.sign_in_count %></p>
        <p><strong>Activation status: </strong> <%= @user.deleted_at ? "Deactivated on #{@user.deleted_at.strftime("%b %d, %Y")}" : "Active" %></p> 
        <p><%= link_to "View user's training", lessons_user_path(@user) %></p>
        <p><%= link_to "View user's timecards", admin_timecards_path(@user) %></p> 
      <% else %>
        <%= render "approve_buttons" %>
      <% end %>
      <p><%= link_to "Edit user's details", edit_user_path(@user) if policy(@user).edit? %></p>
    </div>
  </div>
</div>

app/views/users/training_videos.html.erb
<h4 class="display-4 text-center">Training Records: <%= @user.first_last %></h4>
<h5 class="mt-4">Complete:</h5>
<% if @training_videos_complete.any? %>
  <ul>
    <% @training_videos_complete.each do |v| %>
      <li><%= link_to v.title, training_video_path(v) %></li>
    <% end %>
  </ul>
<% else %>
  <p>This person hasn't finished any videos yet.</p>
<% end %>
<h5 class="mt-4">Not Complete:</h5>
<% if @training_videos_incomplete.any? %>
  <ul>
    <% @training_videos_incomplete.each do |v| %>
      <li><%= link_to v.title, training_video_path(v) %></li>
    <% end %>
  </ul>
<% else %>
  <p>This person has completed all training videos.</p>
<% end %>
<hr>
<div class="row">
  <%= link_to "View user details", user_path(@user), class: "mx-auto" %>
</div>