config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  # Routes for users to register and edit their logins & profiles
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Routes for users to CRUD their own timecards:
  resources :timecards

  # Routes for the document library
  resources :documents, except: %i[new edit]

  # Routes for lessons
  resources :completions, only: :destroy
  resources :lessons do
    member do
      post 'completions', to: 'completions#create'
      get 'users'
    end
  end

  # Administration related routes:
  scope '/admin' do
    resources :users, except: %i[new create] do
      member do
        get 'lessons'
        patch 'deactivate'
        patch 'reactivate'
        patch 'approve'
        delete 'reject'
      end
    end

    # Training completions index
    resources :completions, only: :index

    # Admin timecard index and filters
    get 'timecards/(:user_id)', to: 'timecards#admindex', as: 'admin_timecards'

    # Bulletin management
    resources :bulletins, except: %i[show index]

    # Document library
    resources :documents, only: %i[new edit]
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # Master class, defines one training requirement. Various resources can belong
  # to it.

  # Associations:
  has_many :completions, dependent: :destroy
  has_many :users, through: :completions
  has_one :video, dependent: :destroy, autosave: true, inverse_of: :lesson
  accepts_nested_attributes_for :video

  # Validations:
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 1000 }

  # Scopes:
  default_scope { order(:title) }
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def new
    @lesson ||= Lesson.new
    authorize @lesson
    @lesson.build_video
  end

  def create
    @lesson = Lesson.new(lesson_params[:lesson])
    authorize @lesson
    if @lesson.save
      flash[:success] = 'Training video created!'
      redirect_to lesson_path(@lesson)
    else
      flash.now[:danger] = 'Could not create video.'
      render :new
    end
  end

  def show
    @lesson = get_lesson
    @user = current_user
    if @user.lessons.exists?(@lesson.id)
      @completion = @user.completions.where(lesson_id: @lesson.id).first
    end
  end

  def edit
    @lesson ||= get_lesson
  end

  def update
    @lesson = get_lesson
    if @lesson.update(lesson_params[:lesson])
      flash[:success] = 'Training video updated!'
      redirect_to lesson_path(@lesson)
    else
      flash.now[:danger] = 'Could not update video'
      render :edit
    end
  end

  def index
    @user = current_user
    authorize Lesson
    @lessons_complete = @user.lessons.all
    @lessons_incomplete = Lesson.all.order(:title).to_a - @lessons_complete.to_a
  end

  def destroy
    @lesson = get_lesson
    if @lesson.delete
      flash[:success] = 'Video deleted!'
      redirect_to lessons_path
    else
      flash.now[:danger] = 'Could not delete video.'
      render :edit
    end
  end

  def users
    @lesson = get_lesson
    authorize @lesson
    @users_complete = @lesson.users.all
    @users_incomplete = (User.all.to_a - @users_complete.to_a)
  end

  private

  def get_lesson
    lesson = Lesson.includes(:video).find(params[:id])
    authorize lesson
    lesson
  end

  def lesson_params
    params.permit(lesson: [:title, :description, video_attributes: [:url]])
  end
end

app/views/lessons/_form.html.erb
<%= validation_fails @lesson %>
<div class="row justify-content-center">
  <div class="col">
    <div class="card border-warning p-3 mb-4">
      <h3 class="card-title">Important Information</h3>
      <p class="card-text">
        This website can accept any YouTube video, listed or unlisted, to show 
        trainees. Listed videos show up in YouTube searches and suggestions, while unlisted
        videos can only be accessed with the exact address. <strong>This 
        does not mean they are private</strong>; anybody with the link (including
        everyone who has access to this website) can share it freely. It's 
        even possible to randomly discover an unlisted video by trial and error. There 
        are services available, such as vimeo, which offer truly private video hosting, 
        but not for free. 
      </p>
      <p class="card-text">
        You can add existing youtube videos, or you can upload your own. You'll need a 
        Google account, and pay attention to privacy settings before you publish 
        the video if you'd like to set it as unlisted. There is more help 
        <a href="https://support.google.com/youtube/answer/57407?co=GENIE.Platform%3DDesktop&hl=en">here</a>
        if you need it. 
      </p>
    </div>
  </div>
</div>
<%= form_for @lesson do |lesson| %>
  <%= lesson.fields_for :video, @lesson.video do |video| %>
    <div class = "form-group">
      <%= video.label "YouTube address" %>
      <%= video.text_field :url, class: "form-control", required: true  %>
      <small id="urlHelp" class="form-text text-muted">
        Pull up the youtube video you want to add, copy and paste its address here. 
      </small>
    </div>
  <% end %>
  <div class = "form-group">
    <%= lesson.label :title %>
    <%= lesson.text_field :title, class: "form-control form-control-lg", required: true %>
    <small id="titleHelp" class="form-text text-muted">
      This will be the name used for this video on this website. It's unrelated to the YouTube title.  
    </small>
  </div>
  <div class = "form-group">
    <%= lesson.label :description %>
    <%= lesson.text_area :description, class: "form-control", rows: "5", required: true %>
    <small id="descriptionHelp" class="form-text text-muted">
      This will show up below the video when people watch it. It's unrelated to the description on YouTube.
      It's formatted using <a href="https://en.support.wordpress.com/markdown-quick-reference/">markdown</a>.
    </small>
  </div>
  <%= lesson.submit "Save!", class: "btn btn-lg btn-success my-4" %>
<% end %>

app/views/lessons/_index_table.html.erb
<h5><%= which_listing %>:</h5>
<table class="table table-hover my-4">
  <% if lessons.any? %>
    <% lessons.each do |l| %>
      <tr onclick="window.location='<%= lesson_path(l) %>'">
        <td><%= link_to l.title, lesson_path(l) %></td>
      </tr>
    <% end %>
  <% else %>
    <tr><td>None</td><tr>
  <% end %>
</table>

app/views/lessons/edit.html.erb
<h4 class="display-4 text-center my-4">Edit Video Details</h2>

<%= render "form" %>

<div class="row justify-content-center"%>
    <%= button_to "Delete video", lesson_path(@lesson), 
    data: {confirm: "Are you sure you want to delete this video? This
    will also delete all related training records."},
    method: :delete, class: "btn btn-danger text-center" %>
</div>

app/views/lessons/index.html.erb
<h4 class="display-4 text-center my-4">My Training</h4>
<%= render partial: 'index_table', locals: {which_listing: "Not Complete", lessons: @lessons_incomplete} %>
<%= render partial: 'index_table', locals: {which_listing: "Complete", lessons: @lessons_complete} %>
<%= link_to "Add Video", new_lesson_path, class: "btn btn-primary text-center my-2"  if policy(Lesson).new? %>

app/views/lessons/new.html.erb
<h4 class="display-4 text-center my-4">Add New Video</h2>
<%= render "form" %>

app/views/lessons/show.html.erb
<div class="embed-responsive embed-responsive-16by9">
  <iframe type="text/html" class="embed-responsive-item"
    src="https://www.youtube.com/embed/<%= @lesson.video.yt_id %>?modestbranding=1&rel=0&showinfo=0" 
    frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen>
  </iframe>
</div>
<div class="card my-3 p-3">
    <h4 class="card-title"><%= @lesson.title %></h4>
     <p class="card-text"><%= render inline: markdown.render(@lesson.description) %></p>
</div>
<div class="col card p-3 my-4">
  <% if @completion %>
    <p>Signed off <%=@completion.created_at.strftime("%A, %b %d %Y") %></p>
    <%= button_to "I haven't actually completed this training.", completion_path(@completion), 
      data: {confirm: "Are you sure you want to delete this training record?"},
      class: "btn btn-outline-danger btn-sm", method: :delete %>
  <% else %>
    <%= button_to "I solemnly swear that I have completed this training.",
      completions_lesson_path(@lesson), method: :post, class: "btn btn-primary btn-block my-2" %>
  <% end %>
</div>
<div class="row">
  <%= link_to "List users who have completed this video", users_lesson_path(@lesson), class: "text-center mx-auto my-2" if policy(@lesson).users? %>
</div>
<div class="row">
  <%= link_to "Edit Video", edit_lesson_path(@lesson), class: "text-center mx-auto my-2" if policy(@lesson).edit? %>
</div>

app/views/lessons/users.html.erb
<h4 class="display-4 text-center my-4"><%= @lesson.title %></h4>
<h5 class="mt-4">Complete:</h5>
<% if @users_complete.any? %>
  <ul>
    <% @users_complete.each do |u| %>
      <li><%= link_to  u.first_last, user_path(u) %></li>
    <% end %>
  </ul>
<% else %>
  <p>Nobody has finished this video yet.</p>
<% end %>

<h5 class="mt-4">Not complete: </h5>
<% if @users_incomplete.any?%>
  <ul>
    <% @users_incomplete.each do |u| %>
      <li><%= link_to u.first_last, user_path(u) %></li>
    <% end %>
  </ul>
<% else %>
  <p>Everyone has completed this video.</p>
<% end %>
<hr>
<div class="row">
  <%= link_to "View video", lesson_path(@lesson), class: "mx-auto" %>
</div>