config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  # Routes for users to register and edit their logins & profiles
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Routes for users to CRUD their own timecards:
  resources :timecards

  # Routes for the document library
  resources :documents, except: %i[new edit]

  # Routes for lessons
  resources :completions, only: :destroy
  resources :lessons do
    member do
      post 'completions', to: 'completions#create'
      get 'users'
    end
  end

  # Administration related routes:
  scope '/admin' do
    resources :users, except: %i[new create] do
      member do
        get 'lessons'
        patch 'deactivate'
        patch 'reactivate'
        patch 'approve'
        delete 'reject'
      end
    end

    # Training completions index
    resources :completions, only: :index

    # Admin timecard index and filters
    get 'timecards/(:user_id)', to: 'timecards#admindex', as: 'admin_timecards'

    # Bulletin management
    resources :bulletins, except: %i[show index]

    # Document library
    resources :documents, only: %i[new edit]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  # Pundit error handling
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Helper file for the navgar:
  helper NavigationHelper

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name badge_number])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name badge_number])
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Hash of bootstrap message types vs rails message types.
  BOOTSTRAP_FLASH_MSG = {
    success: 'success',
    error: 'warning',
    alert: 'danger',
    notice: 'info'
  }.freeze

  # Converts rails flash messages to names that bootstrap expects, for proper styling
  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type)
  end

  # Instantiates redcarpet to render markdown
  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
  end

  # Validation fails
  def validation_fails(record)
    if record.errors.any?
      render partial: 'application/validation_fails', locals: { record: record }
    end
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def dynamic_navbar_links
    if user_signed_in?
      render 'application/navigation/logged_in_links'
    else
      render 'application/navigation/logged_out_links'
    end
  end

  def admin_links
    render 'application/navigation/admin_links' if current_user.trainer?
  end
end

app/views/application/navigation/_admin_links.html.erb
<div class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Administration
  </a>
  <div class="dropdown-menu active" aria-labelledby="navbarDropdown"}>
    <%= link_to 'Users', users_path, class: 'dropdown-item' %>
    <%= link_to 'Timecards', admin_timecards_path, class: 'dropdown-item' %>
    <%= link_to 'Training', completions_path, class: 'dropdown-item' %>
    <%= link_to 'Upload to Library', new_document_path, class: 'dropdown-item' %>
  </div>
</div>

app/views/application/navigation/_logged_in_links.html.erb
<div class="navbar-nav mr-auto">
  <%= link_to "Training", lessons_path, class: "nav-item nav-link" %>
  <%= link_to "Timecards", timecards_path, class: "nav-item nav-link" %>
  <%= link_to "Library", documents_path, class: "nav-item nav-link" %>
  <%= admin_links %>
</div>
<%= link_to edit_user_registration_path, class: "navbar-text p-2" do %>
  <%= current_user.first_last(40) %>,
  <%= current_user.role.capitalize %>
<% end %>
<%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger mx-1" %> 

app/views/application/navigation/_logged_out_links.html.erb
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary ml-auto" %>
<%= link_to "Log in", new_user_session_path, class: "btn btn-outline-success mx-1" %>

app/views/application/navigation/_navbar.html.erb
<div class="container-fluid">
  <nav class="row navbar navbar-expand-md navbar-dark bg-dark">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa fa-shield fa-lg"></i>
      Monroe County
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent"> 
      <%= dynamic_navbar_links %>
    </div>
  </nav>
</div>